import { Download, FileText } from "lucide-react";

function escapeHtml(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function downloadBlob(filename, html) {
  const blob = new Blob(["\ufeff", html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".doc") ? filename : `${filename}.doc`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function downloadWeeklyDoc(doc) {
  const days = doc.dayColumns || [];
  const dayHeader = days.map((d) => `<th style="padding:6px 5px;border:1px solid #3a4553;">${escapeHtml(d.label)}</th>`).join("");

  const dayRows = (doc.dayRows || [])
    .map(
      (r) => `<tr>
      <td style="padding:6px 8px;border:1px solid #3a4553;">${escapeHtml(r.dateLabel)}</td>
      <td style="padding:6px 8px;border:1px solid #3a4553;text-align:center;">${r.logs}</td>
      <td style="padding:6px 8px;border:1px solid #3a4553;text-align:center;">${escapeHtml(r.hours)}</td>
      <td style="padding:6px 8px;border:1px solid #3a4553;text-align:center;">${r.employees}</td>
    </tr>`
    )
    .join("");

  const projectRows = (doc.projectRows || [])
    .map((r) => {
      const dailyCells = days
        .map(
          (d) =>
            `<td style="padding:5px 4px;border:1px solid #3a4553;text-align:center;">${r.daily?.[d.key] ?? 0}</td>`
        )
        .join("");
      return `<tr>
        <td style="padding:5px 6px;border:1px solid #3a4553;text-align:center;">${r.sno}</td>
        <td style="padding:5px 6px;border:1px solid #3a4553;white-space:nowrap;">${escapeHtml(r.code)}</td>
        <td style="padding:5px 6px;border:1px solid #3a4553;">${escapeHtml(r.name)}</td>
        ${dailyCells}
        <td style="padding:5px 6px;border:1px solid #3a4553;text-align:center;font-weight:700;">${r.totalLogs}</td>
        <td style="padding:5px 6px;border:1px solid #3a4553;text-align:center;">${escapeHtml(r.totalHours)}</td>
        <td style="padding:5px 6px;border:1px solid #3a4553;text-align:center;">${r.employees}</td>
      </tr>`;
    })
    .join("");

  const k = doc.kpis || {};
  const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta charset="utf-8"><title>${escapeHtml(doc.title)}</title>
<style>
  body { font-family: Calibri, Arial, sans-serif; background:#2b3038; color:#e8eef5; margin:0; padding:28px; }
  h1 { color:#8ec5ff; font-size:28pt; margin:0 0 6px; font-family: Georgia, serif; }
  .brand { float:right; color:#9fb0c3; font-size:10pt; margin-top:8px; }
  .period { color:#c5d0dc; font-size:12pt; margin-bottom:18px; clear:both; }
  .kpis { width:100%; border-collapse:separate; border-spacing:10px 0; margin:0 0 22px; }
  .kpis td { background:#353b45; border:1px solid #4a5563; padding:12px 10px; text-align:center; width:25%; }
  .kpis .v { font-size:18pt; font-weight:700; color:#fff; }
  .kpis .l { font-size:9pt; color:#9fb0c3; margin-top:4px; }
  table.data { width:100%; border-collapse:collapse; font-size:10pt; margin-bottom:22px; }
  table.data th { background:#2f6fed; color:#fff; padding:8px 6px; border:1px solid #3a4553; text-align:center; }
  table.data td { background:#323843; }
  h2 { color:#d7e3f0; font-size:13pt; margin:20px 0 8px; }
  .foot { color:#7d8b9a; font-size:9pt; margin-top:16px; }
</style></head>
<body>
  <div class="brand">${escapeHtml(doc.brand || "aimantra agent — Weekly Time Log Report")}</div>
  <h1>${escapeHtml(doc.title || "Weekly Project Time Log Summary")}</h1>
  <p class="period">Reporting Period: ${escapeHtml(doc.periodLabel || "—")}</p>

  <table class="kpis"><tr>
    <td><div class="v">${escapeHtml(k.totalLogs)}</div><div class="l">Total Time Logs</div></td>
    <td><div class="v">${escapeHtml(k.totalHours)}</div><div class="l">Total Hours Logged</div></td>
    <td><div class="v">${escapeHtml(k.projects)}</div><div class="l">Projects Worked On</div></td>
    <td><div class="v">${escapeHtml(k.employees)}</div><div class="l">Employees Logged Time</div></td>
  </tr></table>

  <h2>Day-wise Overview</h2>
  <table class="data">
    <tr>
      <th>Date</th><th>Total Logs</th><th>Total Hours Logged</th><th>Employees Active</th>
    </tr>
    ${dayRows}
  </table>

  <h2>Project-wise Log Summary (${(doc.projectRows || []).length} projects)</h2>
  <table class="data">
    <tr>
      <th>S.No</th><th>Project Code</th><th>Project Name</th>
      ${dayHeader}
      <th>Total Logs</th><th>Total Hours</th><th>Employees</th>
    </tr>
    ${projectRows}
  </table>

  <p class="foot">Generated by aimantra agent</p>
</body></html>`;

  downloadBlob(doc.downloadName || "Weekly_TimeLog_Report", html);
}

function downloadGenericDoc(doc) {
  const sectionsHtml = (doc.sections || [])
    .map((sec) => {
      const bullets = (sec.bullets || []).map((b) => `<li>${escapeHtml(b)}</li>`).join("");
      const blocks = (sec.blocks || [])
        .map(
          (b) => `
          <h3 style="margin:14px 0 6px;font-size:13pt;color:#0f766e;">${escapeHtml(b.title)}</h3>
          <ul>${(b.lines || []).map((l) => `<li>${escapeHtml(l)}</li>`).join("")}</ul>`
        )
        .join("");
      return `
        <h2 style="margin:22px 0 8px;font-size:14pt;border-bottom:1px solid #cbd5e1;padding-bottom:4px;">
          ${escapeHtml(sec.heading)}
        </h2>
        ${bullets ? `<ul>${bullets}</ul>` : ""}
        ${blocks}`;
    })
    .join("");

  const metaRows = (doc.meta || [])
    .map(
      (m) =>
        `<tr>
          <td style="padding:6px 10px;border:1px solid #e2e8f0;background:#f8fafc;font-weight:600;width:32%;">${escapeHtml(m.label)}</td>
          <td style="padding:6px 10px;border:1px solid #e2e8f0;">${escapeHtml(m.value)}</td>
        </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${escapeHtml(doc.title)}</title></head>
<body style="font-family:Calibri,Arial,sans-serif;color:#0f172a;max-width:800px;margin:24px auto;">
  <p style="color:#0f766e;font-size:11pt;letter-spacing:2px;text-transform:uppercase;margin:0;">Detailed Design · aimantra agent</p>
  <h1 style="margin:6px 0 4px;font-size:22pt;">${escapeHtml(doc.title)}</h1>
  ${doc.subtitle ? `<p style="margin:0 0 16px;color:#475569;font-size:12pt;">${escapeHtml(doc.subtitle)}</p>` : ""}
  <table style="border-collapse:collapse;width:100%;font-size:11pt;margin-bottom:18px;">${metaRows}</table>
  ${sectionsHtml}
</body></html>`;

  downloadBlob(doc.downloadName || "AskAI_Report", html);
}

export function downloadReportDoc(doc) {
  if (!doc) return;
  if (doc.kind === "weekly_timelog") downloadWeeklyDoc(doc);
  else downloadGenericDoc(doc);
}

function WeeklyReportView({ doc, fullPage }) {
  const days = doc.dayColumns || [];
  const k = doc.kpis || {};

  return (
    <div
      className={`overflow-hidden border border-slate-700 bg-[#2b3038] text-slate-100 shadow-lg ${
        fullPage ? "rounded-2xl" : "rounded-xl"
      }`}
    >
      <div className={`border-b border-slate-600/80 ${fullPage ? "px-5 py-4" : "px-3.5 py-3"}`}>
        <div className="flex items-start justify-between gap-2">
          <div className="min-w-0">
            <p className="text-[9px] font-semibold uppercase tracking-[0.14em] text-slate-400">
              {doc.brand || "aimantra agent — Weekly Time Log Report"}
            </p>
            <h4
              className={`mt-1 font-serif font-bold leading-snug text-sky-300 ${
                fullPage ? "text-[22px]" : "text-[15px]"
              }`}
            >
              {doc.title}
            </h4>
            <p className={`mt-1 text-slate-300 ${fullPage ? "text-[13px]" : "text-[11px]"}`}>
              Reporting Period: {doc.periodLabel}
            </p>
          </div>
          <FileText size={fullPage ? 20 : 16} className="mt-1 shrink-0 text-slate-400" />
        </div>

        <div className={`mt-3 grid gap-1.5 ${fullPage ? "grid-cols-4" : "grid-cols-2"}`}>
          {[
            { l: "Total Time Logs", v: k.totalLogs },
            { l: "Total Hours Logged", v: k.totalHours },
            { l: "Projects Worked On", v: k.projects },
            { l: "Employees Logged Time", v: k.employees },
          ].map((x) => (
            <div
              key={x.l}
              className={`rounded-md border border-slate-600 bg-[#353b45] text-center ${
                fullPage ? "px-3 py-3" : "px-2 py-2"
              }`}
            >
              <p
                className={`font-bold text-white leading-none ${
                  fullPage ? "text-[22px]" : "text-[15px]"
                }`}
              >
                {x.v ?? 0}
              </p>
              <p className="mt-1 text-[8.5px] font-medium uppercase tracking-wide text-slate-400">
                {x.l}
              </p>
            </div>
          ))}
        </div>
      </div>

      <div
        className={`space-y-3 overflow-auto px-3 py-3 ${
          fullPage ? "max-h-[calc(100vh-280px)] px-5 py-4" : "max-h-[340px]"
        }`}
      >
        <div>
          <p className="mb-1.5 text-[11px] font-semibold text-slate-200">Day-wise Overview</p>
          <div className="overflow-x-auto rounded-md border border-slate-600">
            <table className="w-full min-w-[320px] border-collapse text-[10px]">
              <thead>
                <tr className="bg-[#2f6fed] text-white">
                  <th className="px-2 py-1.5 text-left font-semibold">Date</th>
                  <th className="px-2 py-1.5 text-center font-semibold">Logs</th>
                  <th className="px-2 py-1.5 text-center font-semibold">Hours</th>
                  <th className="px-2 py-1.5 text-center font-semibold">Employees</th>
                </tr>
              </thead>
              <tbody>
                {(doc.dayRows || []).map((r) => (
                  <tr key={r.date} className="border-t border-slate-600 bg-[#323843]">
                    <td className="px-2 py-1.5 whitespace-nowrap">{r.dateLabel}</td>
                    <td className="px-2 py-1.5 text-center">{r.logs}</td>
                    <td className="px-2 py-1.5 text-center">{r.hours}</td>
                    <td className="px-2 py-1.5 text-center">{r.employees}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div>
          <p className="mb-1.5 text-[11px] font-semibold text-slate-200">
            Project-wise Log Summary ({(doc.projectRows || []).length} projects)
          </p>
          {doc.emptyMessage && !doc.projectRows?.length ? (
            <p className="text-[11px] text-slate-400">{doc.emptyMessage}</p>
          ) : (
            <div className="overflow-x-auto rounded-md border border-slate-600">
              <table className="w-full min-w-[640px] border-collapse text-[9.5px]">
                <thead>
                  <tr className="bg-[#2f6fed] text-white">
                    <th className="px-1.5 py-1.5 font-semibold">S.No</th>
                    <th className="px-1.5 py-1.5 text-left font-semibold">Code</th>
                    <th className="px-1.5 py-1.5 text-left font-semibold">Project Name</th>
                    {days.map((d) => (
                      <th key={d.key} className="px-1 py-1.5 font-semibold whitespace-nowrap">
                        {d.label}
                      </th>
                    ))}
                    <th className="px-1.5 py-1.5 font-semibold">Logs</th>
                    <th className="px-1.5 py-1.5 font-semibold">Hours</th>
                    <th className="px-1.5 py-1.5 font-semibold">Emp</th>
                  </tr>
                </thead>
                <tbody>
                  {(doc.projectRows || []).map((r) => (
                    <tr key={`${r.code}-${r.sno}`} className="border-t border-slate-600 bg-[#323843]">
                      <td className="px-1.5 py-1 text-center text-slate-300">{r.sno}</td>
                      <td className="px-1.5 py-1 whitespace-nowrap font-semibold text-sky-200">
                        {r.code}
                      </td>
                      <td className="px-1.5 py-1 max-w-[140px] truncate" title={r.name}>
                        {r.name}
                      </td>
                      {days.map((d) => (
                        <td key={d.key} className="px-1 py-1 text-center">
                          {r.daily?.[d.key] ?? 0}
                        </td>
                      ))}
                      <td className="px-1.5 py-1 text-center font-bold">{r.totalLogs}</td>
                      <td className="px-1.5 py-1 text-center whitespace-nowrap">{r.totalHours}</td>
                      <td className="px-1.5 py-1 text-center">{r.employees}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>

      <div className="flex items-center gap-2 border-t border-slate-600 bg-[#252a31] px-3.5 py-2.5">
        <button
          type="button"
          onClick={() => downloadReportDoc(doc)}
          className="inline-flex items-center gap-1.5 rounded-lg bg-[#2f6fed] px-2.5 py-1.5 text-[11px] font-semibold text-white hover:bg-blue-600"
        >
          <Download size={12} />
          Download .doc
        </button>
        <p className="text-[9px] text-slate-500">Matches Weekly Time Log Summary format</p>
      </div>
    </div>
  );
}

function GenericReportView({ doc, onOpenProject, fullPage = false }) {
  return (
    <div
      className={`overflow-hidden border border-slate-200 bg-[#fbfaf7] shadow-sm ${
        fullPage ? "rounded-2xl" : "rounded-xl"
      }`}
    >
      <div className={`border-b border-slate-200 bg-white ${fullPage ? "px-5 py-4" : "px-3.5 py-3"}`}>
        <div className="flex items-start justify-between gap-2">
          <div className="min-w-0">
            <p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-teal-700">
              Document report
            </p>
            <h4
              className={`mt-0.5 font-bold text-slate-900 leading-snug ${
                fullPage ? "text-[18px]" : "text-[13px]"
              }`}
            >
              {doc.title}
            </h4>
            {doc.subtitle && (
              <p className={`mt-0.5 text-slate-500 leading-snug ${fullPage ? "text-[13px]" : "text-[12px]"}`}>
                {doc.subtitle}
              </p>
            )}
          </div>
          <FileText size={fullPage ? 22 : 18} className="mt-0.5 shrink-0 text-slate-400" />
        </div>
      </div>

      <div className={fullPage ? "px-5 py-4" : "px-3.5 py-2.5"}>
        <div className="overflow-hidden rounded-lg border border-slate-200 bg-white">
          {(doc.meta || []).map((m, i) => (
            <div
              key={i}
              className={`grid text-[11.5px] ${
                fullPage ? "grid-cols-[140px_1fr] text-[13px]" : "grid-cols-[110px_1fr]"
              } ${i > 0 ? "border-t border-slate-100" : ""}`}
            >
              <div className="bg-slate-50 px-2.5 py-1.5 font-semibold text-slate-500">{m.label}</div>
              <div className="break-words px-2.5 py-1.5 text-slate-800">{m.value}</div>
            </div>
          ))}
        </div>

        <div className={`mt-3 space-y-3 ${fullPage ? "max-h-[calc(100vh-320px)] overflow-y-auto" : ""}`}>
          {(doc.sections || []).map((sec, i) => (
            <div key={i}>
              <p className="mb-1 border-b border-slate-200 pb-1 text-[11px] font-bold uppercase tracking-wide text-slate-700">
                {sec.heading}
              </p>
              {(sec.bullets || []).length > 0 && (
                <ul className="space-y-1">
                  {sec.bullets.map((b, bi) => (
                    <li key={bi} className="flex gap-1.5 text-[11.5px] leading-snug text-slate-700">
                      <span className="shrink-0 text-teal-600">•</span>
                      <span className="min-w-0 break-words">{b}</span>
                    </li>
                  ))}
                </ul>
              )}
              {(sec.blocks || []).map((block, bi) => (
                <div key={bi} className="mt-2 rounded-lg border border-slate-100 bg-white/80 px-2.5 py-2">
                  <p className="text-[12px] font-semibold text-teal-800">{block.title}</p>
                  <ul className="mt-1 space-y-0.5">
                    {(block.lines || []).map((line, li) => (
                      <li key={li} className="pl-1 text-[11px] text-slate-600">
                        {line}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          ))}
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-2 border-t border-slate-200 bg-white px-3.5 py-2.5">
        <button
          type="button"
          onClick={() => downloadReportDoc(doc)}
          className="inline-flex items-center gap-1.5 rounded-lg bg-slate-900 px-2.5 py-1.5 text-[11px] font-semibold text-white hover:bg-slate-800"
        >
          <Download size={12} />
          Download .doc
        </button>
        {doc.projectId && onOpenProject && (
          <button
            type="button"
            onClick={() => onOpenProject(doc.projectId)}
            className="text-[11px] font-semibold text-teal-700 hover:underline"
          >
            Open project page →
          </button>
        )}
      </div>
    </div>
  );
}

export default function ReportDoc({ doc, onOpenProject, fullPage = false, compact = false }) {
  if (!doc) return null;
  if (doc.kind === "weekly_timelog") {
    return <WeeklyReportView doc={doc} fullPage={fullPage} compact={compact} />;
  }
  if (doc.kind === "document") {
    return <GenericReportView doc={doc} onOpenProject={onOpenProject} fullPage={fullPage} />;
  }
  return null;
}
